/**
 * Arguments accepted by any MailerTransport.send().
 * Mirrors Resend's API surface, but kept transport-agnostic so Console
 * can implement the same interface.
 */
export interface SendArgs {
  /** Recipient(s) — string for one, array for many (max 50 per Resend). */
  to: string | string[]
  /** Email subject line. */
  subject: string
  /** Pre-rendered HTML body (mutually exclusive with `react`). */
  html?: string
  /** Plain-text fallback. If omitted and `html` is set, auto-generated by Resend. */
  text?: string
  /** React Email component (Node.js only). Resend renders it server-side. */
  react?: React.ReactNode
  /** Reply-To override. */
  replyTo?: string
  /** Tags for Resend dashboard segmentation. */
  tags?: Array<{ name: string; value: string }>
  /** Optional Resend idempotency key (24h TTL, max 256 chars). */
  idempotencyKey?: string
}

/**
 * Common interface every transport implements. Return shape is intentionally
 * narrow — either success with an id, or failure with a human-readable message.
 * Transports must NOT throw on API errors (Resend's SDK returns `{data, error}`
 * instead of throwing; Console follows the same convention).
 */
export interface MailerTransport {
  send(args: SendArgs): Promise<{ id: string } | { error: string }>
}